//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace houseListings
{
    using System;
    using System.Collections.Generic;
    
    public partial class House_All
    {
        public int house_id { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> bedroom { get; set; }
        public Nullable<int> bathroom { get; set; }
        public Nullable<int> zip { get; set; }
        public string city { get; set; }
        public string us_state { get; set; }
        public Nullable<int> sqft { get; set; }
        public Nullable<int> house_year { get; set; }
    }
}
